language: ruby
bundler_args: --without production
before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:migrate
script:
- bundle exec rspec
